[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src', '@solmate=lib/solmate/src']
# Giving foundry access to the broadcast folder, in this case to allow it see most recently deployed contract
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[fuzz]
runs = 10000
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
